- WIN-DEV-DEPLOY.md
Добавил гайд по развертыванию на Windows WSL
> Add Windows dev deploy guide

- .github/workflows/deploy.yml
- DEV-DEPLOY.md
- WIN-DEV-DEPLOY.md
- src/grabber/nsreg/settings.py
- src/telegram_bot/__main__.py
Добавил развертывание на dev сервере при push'е в реппозиторий
Добавил докерфайлы для сборки джанго и парсеров+бот
Подправил все файлы для прохождения проверки линтером
Исправил в темплейте about-us ошибки
Подправил скрипт runspiders.sh, не нужно будет после создания нового файла со спайдером добавлять его в скрипт
PS
Большинство изменений не видно, т.к. dev была скопирована c deployment-dev
> Deployment dev

- src/grabber/nsreg/base_site_spider.py
- src/grabber/nsreg/spiders/multi_site_spider1.py
- src/grabber/nsreg/spiders/multi_site_spider2.py
- src/grabber/nsreg/spiders/multi_site_spider3.py
- src/grabber/nsreg/spiders/multi_site_spider4.py
- src/grabber/nsreg/spiders/multi_site_spider5.py
Провёл рефакторинг с применением композиции и сделал 5 мультипарсеров
> refactor spiders composition

- src/grabber/nsreg/pipelines.py
Reverts ecodomen/nsreg-watcher#62
> Revert "Feature add price table"

- src/grabber/nsreg/spiders/nsreg_openprovider.py
добавлен файл nsreg_openprovider
> добавлен файл nsreg_openprovider.py

- src/grabber/nsreg/spiders/nsreg_maxname.py
- src/grabber/nsreg/spiders/nsreg_timeweb.py
> Add timeweb.py and maxname.py

- src/website/catalog/forms.py
- src/website/catalog/views.py
- src/website/website/templates/companies-sort.html
Доработал сортировку, чтобы можно было по всем доступным опциям сортировать "от меньшего к большему" и обратно #78 .
> Add reverse sort feature #78

- src/grabber/nsreg/spiders/nsreg_klondike.py
Новый спайдер для klondike-studio
> Update nsreg_klondike.py with BaseSpiderComponent

- src/grabber/nsreg/spiders/nsreg_centralreg.py
Простите, что-то сломалось у меня в линуксе и пришлось заново всё делать. 
Поправил ошибки с линтером, теперь всё должно быть нормально
> Add parser to cite centralreg.ru

- src/website/catalog/views.py
Поправил ошибку на главной при запуске сайта с пустой базой (без запуска спайдеров).
> Fix IndexError on main page when no parsed data

- src/grabber/nsreg/spiders/nsreg_r01.py
Исправленный парсер для r01.ru #100
> Fix parser for r01.ru

- src/grabber/nsreg/spiders/nsreg_elastichosting.py
https://github.com/ecodomen/nsreg-watcher/issues/94
> add parser for elastichosting #94

- src/grabber/nsreg/spiders/nsreg_flexbe.py
Парсер для https://flexbe.ru #96
> Add nsreg_flexbe spider

- src/grabber/nsreg/spiders/nsreg_starnames.py
> add nsreg_starnames.py

- src/grabber/nsreg/spiders/nsreg_domeny.py
Переписал парсер через BaseSpiderComponent #108
> Fix nsreg_domeny with BaseSpider

- src/grabber/nsreg/base_site_spider.py
Немного поправил получение имени сайта
> Fix base_spider site_name

- src/grabber/nsreg/spiders/nsreg_pinspb.py
Добавлен spider nsreg_pinspb (closes #101)
> Добавлен spider nsreg_pinspb (#101)

- src/grabber/nsreg/spiders/nsreg_nic.py
> Rewrite parser for nic.ru

- src/grabber/nsreg/spiders/nsreg_beget.py
> Rewrite spider for beget.com

- src/grabber/nsreg/spiders/nsreg_domenus.py
> Add spider for www.domenus.ru

- src/grabber/nsreg/spiders/nsreg_2domains.py
> Rewrite spider for 2domains.ru

- src/grabber/nsreg/spiders/nsreg_runetproekt.py
> Fix spider runetproekt.ru

- src/grabber/nsreg/spiders/nsreg_salenames.py
> Fix spider salenames.ru

- src/grabber/nsreg/spiders/nsreg_spacewebdomains.py
> Fix spider spacewebdomains.py

- src/grabber/nsreg/spiders/nsreg_getname.py
> Add spider for getname.ru

- src/grabber/nsreg/spiders/nsreg_domainsnethouse.py
> Add spider for domains.nethouse.ru

- src/grabber/nsreg/spiders/nsreg_domainer.py
> Add spider domainer.ru

- src/grabber/nsreg/spiders/nsreg_altnames.py
> Rewrite spider for altnames.ru

- src/grabber/nsreg/spiders/nsreg_opencom.py
- src/grabber/nsreg/spiders/nsreg_openreg.py
> Add Spiders opencom.ru openreg.ru

- src/grabber/nsreg/spiders/multi_site_spider3.py
- src/grabber/nsreg/spiders/nsreg_namebit.py
Перенес namebit из мультиспайдера в отдельный, т.к. xpath, указанный там не работает для этого сайта.
> Move namebit parser from multi_site_spider3.py to separate spider

- src/website/catalog/views.py
Поправил баг с дубликатами в поиске https://github.com/ecodomen/nsreg-watcher/issues/168
Поправил баг с отображением регистраторов https://github.com/ecodomen/nsreg-watcher/issues/193
> Fix registrator_list

- src/website/catalog/models.py
- src/website/catalog/views.py
- src/website/website/templates/base.html
- src/website/website/templates/navbar.html
- src/website/website/templates/registrator-details.html
- src/website/website/templates/registrator-list.html
Добавил историю цен на страницу деталей регистратора (**/partner/<int:id>**)
На страницу можно перейти нажав на имя регистратора в списке регистраторов. 
На странице отображаются:
- Имя регистратора
- Город
- nic_handle1
- nic_handle2
- Ссылка на сайт
- История цен с датой парса 
Closes  #56
> История изменения цен на странице registrator_detail

- src/grabber/nsreg/spiders/nsreg_capnames.py
- src/grabber/nsreg/spiders/nsreg_namebit.py
- src/grabber/nsreg/spiders/nsreg_royaldomains.py
Closes #240 
Добавил задержку между запросами для спайдеров, которые блокировались регистраторами.
> Fix Connection Refused for spiders namebit.ru capnames.ru royaldomains.ru

- src/grabber/nsreg/spiders/nsreg_masterhost.py
Переписан парсер для сайта masterhost.ru
Для того, чтобы стоимость смены регистратора (миграции) спарсилась нормально необходимо изменить код в base_site_spider.py. 
В функции find_price() заменить строку: 
- - - if price.casefold() == ("бесплатно"):
на строку:
+++ if price.casefold() in ("бесплатно", "бесплатный трансфер доменов в зонах .ru, .рф, .su."):
В дальнейшем, возможно, есть смысл пересмотреть работу функцию find_price() по отношению к тому, чтобы применять регулярное выражение также и к строке при сравнении (или нахождение в кортеже) if price.casefold() in ("бесплатно", "бесплатный" ...). Например: 
if re.match(re_pattern, price.casefold()).group(0) in ("бесплатно", "бесплатный"): price = 0
> WIP: Изменение парсера для сайта masterhost.ru

- requirements.txt
- src/grabber/nsreg/models.py
- src/website/catalog/admin.py
- src/website/catalog/models.py
- src/website/catalog/views.py
- src/website/website/templates/registrator-list.html
> WIP: Отображение отсутвующей цены регистратора
